version: "3.7"
services:
  apcontrole-dbserver:
    image: postgres:11-alpine
    container_name: apcontrole-dbserver-container
    environment:
      POSTGRES_USER: apsso-dbuser
      POSTGRES_PASSWORD: apsso-dbpasswd
      POSTGRES_DB: apsso-dbname
    volumes:
      - apsso-pgdata:/var/lib/postgresql/data
    expose:
      - "50000:5432"
  webapp:
    image: registry.gitlab.com/andrepenteado/ap-apcontrole
    container_name: apcontrole-webapp-container
    ports:
      - "30001:8080"
volumes:
  apsso-pgdata: